kind: Pod
apiVersion: v1
metadata:
  name: podwithcm
spec:
  volumes:
  - name: cmvol
    configMap:
      name: myfirstcm
  containers:
  - name: container1
    image: asadhussain1998/first-docker-app:latest
    volumeMounts:
    - name: cmvol
      mountPath: /data/cm
    imagePullPolicy: IfNotPresent
