kind: Pod
apiVersion: v1
metadata:
  name: secretenv
spec:
  containers:
  - name: container1
    image: asadhussain1998/first-docker-app:latest
    envFrom:
    - secretRef:
        name: myfirstsecret
