kind: Pod
apiVersion: v1
metadata:
  name: pod-pv
spec: 
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - name: container1
    image: aamirpinger/logfile_nodejs
    volumeMounts:
    - name: pv-volume
      mountPath: /data
