kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployexample
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: container1
        image: asadhussain1998/first-docker-app:latest
