kind: Pod
apiVersion: v1
metadata: 
  name: podwithsecretvol
spec:
  volumes:
  - name: secvol
    secret:
      secretName: myfirstsecret
  containers:
  - name: container1
    image: asadhussain1998/first-docker-app:latest
    volumeMounts:
    - name: secvol
      mountPath: /secretdata
